### ISSUE TITLE
Invalid package.json

### ISSUE THREAD

**Issue by mohamed-elfakhfekh** [strapi/strapi-template-ecommerce#4]
Please check the current status of the package.json

```
npm view https://github.com/strapi/strapi-template-ecommerce name version
npm ERR! Invalid package.json

.npm/_logs/2021-12-29T10_11_25_557Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'view',
1 verbose cli   'https://github.com/strapi/strapi-template-ecommerce',
1 verbose cli   'name',
1 verbose cli   'version'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose npm-session 698a43f34d557b08
5 verbose stack Error: Invalid package.json
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/view.js:104:30
5 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
5 verbose stack     at Promise.errorAdapter [as _rejectionHandler0] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeify.js:35:34)
5 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
5 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
5 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
5 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
5 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
5 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
5 verbose stack     at processImmediate (internal/timers.js:462:21)
6 verbose cwd /Users/development/strapi
7 verbose Darwin 21.1.0
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "view" "https://github.com/strapi/strapi-template-ecommerce" "name" "version"
9 verbose node v14.17.0
10 verbose npm  v6.14.13
11 error Invalid package.json
12 verbose exit [ 1, true ]
```

**Comment by blueorbitz** [comment]
Reading from this document. It seems to me that this template is strapi default template.

Thus, calling this should work.
`npx create-strapi-app ecom-sample --template ecommerce`
