### ISSUE TITLE
Can't install repo

### ISSUE THREAD

**Issue by ztxone** [strapi/strapi-template-ecommerce#5]
npx create-strapi-app my-app-name --template https://github.com/strapi/strapi-template-ecommerce

? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /Users/user_name/Downloads/my-app-name.
Creating files.
Error: ⛔️ Template installation failed: Command failed: /bin/sh -c npm view https://github.com/strapi/strapi-template-ecommerce name version --silent

    at createProject (/Users/user_name/.config/yarn/global/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createQuickStartProject (/Users/user_name/.config/yarn/global/node_modules/@strapi/generate-new/lib/create-quickstart-project.js:23:3)

**Comment by remidej** [comment]
Hello, you get this error because you're trying to use a v3 template on the v4. The v4 templates moved to a [monorepo](https://github.com/strapi/starters-and-templates/tree/main/packages/templates/ecommerce). Here's the command that should work:

```sh
npx create-strapi-app my-app-name --template ecommerce
```

We need to add a disclaimer on this repo's readme though 👍
